version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/BlazorDemo.Tests"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Blazorise.Bootstrap5"
      - dependency-name: "Blazorise.DataGrid"
      - dependency-name: "Blazorise.Icons.FontAwesome"