version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/BlazorDemo"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/BlazorDemo.Tests"
    schedule:
      interval: "daily"