name: Unit tests, coveralls.io

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: dotnet test BlazorDemo.Tests -e CollectCoverage=true -e CoverletOutputFormat=lcov -e ExcludeByFile="**/_Host.cshtml,**/Error.cshtml.cs"
      - name: Run coveralls.io
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./BlazorDemo.Tests/coverage.info